// flow-typed signature: 154439884f6643403e8f79762b0f7dfe
// flow-typed version: <<STUB>>/diacritics_v1.3.0/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'diacritics'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'diacritics' {
  declare module.exports: any
}

declare module 'remove' {
  // declare type removeType = (string: string) => string
  declare module.exports: (text: string) => string
}
